### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by bla9kdog** [clodeindustrie/figma-linux-font-helper#1]
Hello,

Can you explain how can we use this?

When I try "npm run" I get:

```
Lifecycle scripts included in figma-fonts:
  test
    echo "Error: no test specified" && exit 1

```

Thanks

**Comment by clodeindustrie** [comment]
Hi,

Apologies, I hadn't received any notification of your message :(

So for the moment I only do:
```
node index.js
```

Pretty dodgy but that works, I'll add some details in the README when I have 5mins.

Let me how you go, I have only used it on my box.

Cheers

**Comment by clodeindustrie** [comment]
I'll be honest, this one https://github.com/knguyen0125/figma-linux-font-helper looks a lot better.
